namespace RuntimeComponent1
{
    [bindable]
    [default_interface]
    runtimeclass BlankUserControl : Windows.UI.Xaml.Controls.UserControl
    {
        BlankUserControl();
        String MyProperty{get;};
    }
}
